[project]
name = "apkc-mechanics-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "biopython>=1.87",
    "black>=26.5.1",
    "matplotlib>=3.11.1",
    "numpy<2",
    "pandas>=3.0.5",
    "polarity-engine",
    "scipy<1.14",
    "seaborn>=0.13.2",
    "statannotations>=0.7.2",
    "sympy>=1.14.0",
    "tabulate>=0.10.0",
    "torch==2.2.2",
    "torch-geometric>=2.8.0.post1",
]

[tool.uv.sources]
polarity-engine = { path = "../polarity-engine", editable = true }
